.\" Manpage para changepassroot.
.\" Contact mkl.vegnux@gmail.com para corregir errores.
.TH man 8 "05 Nov 2012" "06.1" "changepassroot man page"
.SH NOMBRE
changepassroot
.SH RESUMEN
changepassroot [PASSWORD]
.SH DESCRIPCION
changepassroot es utilizado por vegnux-installer para modificar la clave de root durante la instalación.
.SH OPCIONES
No tiene opciones o comodines.
.SH VEASE TAMBIEN
vegnux-installer(8), passwd(1), libneonatox(8)
.SH BUGS
No hay bugs conocidos.
.SH AUTORES
Carlos Sánchez (cargabsj175@gmail.com),
.\" 
Nehemias Velázquez (nehe009@gmail.com)
