.\" Manpage para findpart.
.\" Contact mkl.vegnux@gmail.com para corregir errores.
.TH man 8 "05 Nov 2012" "06.1" "findpart man page"
.SH NOMBRE
findpart
.SH RESUMEN
findpart
.SH DESCRIPCION
findpart permite detectar discos, particiones, formato y tamaños de particiones.
.SH OPCIONES
No tiene opciones o comodines.
.SH VEASE TAMBIEN
vegnux-installer(8), libneonatox(8)
.SH BUGS
No hay bugs conocidos.
.SH AUTORES
Carlos Sánchez (cargabsj175@gmail.com),
.\" 
Nehemias Velázquez (nehe009@gmail.com)
