.\" Manpage para infouser.
.\" Contact mkl.vegnux@gmail.com para corregir errores.
.TH man 8 "05 Nov 2012" "06.1" "infouser man page"
.SH NOMBRE
infouser
.SH RESUMEN
infouser [OPCION 1] [OPCION 2] [OPCION 3]
.SH DESCRIPCION
infouser permite modificar la información de un usuario existente.
.SH OPCIONES
  -e	Asistente basico para añadir informacion al usuario.
  -b	Edita informacion sin asistente.
  Ejemplo: infouser -b nombre_usuario nombre_completo numero_telefono
  .SH VEASE TAMBIEN
vegnux-installer(8), useradd(8), libneonatox(8)
.SH BUGS
No hay bugs conocidos.
.SH AUTORES
Carlos Sánchez (cargabsj175@gmail.com),
.\" 
Nehemias Velázquez (nehe009@gmail.com)
