.\" Manpage para libneonatox.
.\" Contact mkl.vegnux@gmail.com para corregir errores.
.TH man 8 "05 Nov 2012" "06.1" "libneonatox man page"
.SH NOMBRE
libneonatox
.SH DESCRIPCION
libneonatox es un conjunto de scripts en bash que permiten simplificar algunas tareas específicas contenidas luego en scripts más complejos
.SH CONTIENE

.SH addnewuser:
permite crear nuevos usuarios para el sistema.
.SH changepassroot:
es utilizado por vegnux-installer para modificar la clave de root durante la instalación.
.SH findpart:
permite detectar discos, particiones, formato y tamaños de particiones.
.SH infouser:
permite modificar la información de un usuario existente.
.SH neoupdate:
obtiene la información de los paquetes que han sufrido modificaciones en los repositorios, permitiendo ver si han sido actualizados o desactualizados.
.SH updategrub2:
crea de manera automática el fichero /boot/grub/grub.cfg que contiene la lista de sistemas operativos disponibles, necesario para el inicio del sistema.

.SH VEASE TAMBIEN
addnewuser(8), changepassroot(8), findpart(8), infouser(8), neoupdate(8), updategrub2(8)
.SH BUGS
No hay bugs conocidos.
.SH AUTORES
Carlos Sánchez (cargabsj175@gmail.com),
.\" 
Nehemias Velázquez (nehe009@gmail.com)
