.\" Manpage para neoupdate.
.\" Contact mkl.vegnux@gmail.com para corregir errores.
.TH man 8 "05 Nov 2012" "06.1" "neoupdate man page"
.SH NOMBRE
neoupdate
.SH RESUMEN
neoupdate -[OPCION]
.SH DESCRIPCION
neoupdate obtiene la información de los paquetes que han sufrido modificaciones en los repositorios, permitiendo ver si han sido actualizados o desactualizados.
.SH OPCIONES
 -h	--help: Muestra esta información.
 -g	--gui: Obtiene información de paquetes nuevos con Interfáz GTK"
 -n	--info: Obtiene información de paquetes nuevos."
 -u	--update: Actualiza los paquetes disponibles"
.SH VEASE TAMBIEN
vegnux-installer(8), nhopkg(8), libneonatox(8)
.SH BUGS
No hay bugs conocidos.
.SH AUTORES
Carlos Sánchez (cargabsj175@gmail.com),
.\" 
Nehemias Velázquez (nehe009@gmail.com)
