.\" Manpage para split4nho.
.\" Contact mkl.vegnux@gmail.com para corregir errores.
.TH man 8 "05 Nov 2012" "06.1" "split4nho man page"
.SH NOMBRE
split4nho
.SH RESUMEN
split4nho -[OPCION]
.SH DESCRIPCION
split4nho crea "rebanadas" de un paquete de código fuente entendibles por nhopkg. Además de hacer la tarea más facil para el empaquetador.
.SH OPCIONES
-h, --help: Muestra esta información.
-t, --tarball-source: Crea solo un pseudo tarball de código fuente. Opcionalmente crea un nhoid compatible con nhopkg.
 .SH VEASE TAMBIEN
vegnux-installer(8), nhopkg(8), libneonatox(8)
.SH BUGS
No hay bugs conocidos.
.SH AUTORES
Carlos Sánchez (cargabsj175@gmail.com),
.\" 
Nehemias Velázquez (nehe009@gmail.com)
