#! /bin/sh
#=========================================================#
# /usr/bin/setlang
# Libreria para Vegnux NeonatoX OS
# Proyecto Venezolano VegnuX <http://www.vegnux.org.ve>
# Por:
# Carlos Sánchez <mkl.vegnux@gmail.com>
# Nehemias Velasquez <nehe009@gmail.com>
# 2007 - 2013
# GPLv3
# This program comes with ABSOLUTELY NO WARRANTY.
#=========================================================#
#===============Inicio de Programa=================#
#Check if running as root.
if [[ "${UID}" != "0" ]]; then
	echo "No eres usuario Root" 
	exit 1
fi

function help(){
    echo "setlang - Proyecto VegnuX 2007-2013 (GPLv3)"
	echo ""
	echo "Uso: setlang [OPTION] [ZONA_HORARIA] o [TECLADO]"
	echo ""
	echo "-h, --help: Muestra esta información."
	echo "-e Menú para establecer el Idioma."
	echo "-b Edita el idioma sin asistente."
	echo "-k Menú para establecer el teclado."
	echo "-n Edita el teclado sin asistente."
}
# menu principal
function set_language(){
SETLANGUAGE="$(zenity --width=400 --height=380 --list --column "No." --column "Language" --title="Establecer Idioma" \
1 "Castellano - Spanish" \
2 "Inglés - English" \
3 "Portugués - Português" \
4 "Ruso - Русский язык")"
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
SETLANGUAGE="0"
exit
fi

if [[ "$SETLANGUAGE" == "1" ]];then
SETLANGUAGE_2="$(zenity --width=400 --height=380 --list --column "" --title="Establecer Idioma - Castellano - Spanish" \
es_AR.iso88591 es_AR.utf8 es_BO.iso88591 es_BO.utf8 es_CL.iso88591 es_CL.utf8  es_CO.iso88591 es_CO.utf8 \
es_CR.iso88591 es_CR.utf8 es_DO.iso88591 es_DO.utf8 es_EC.iso88591 es_EC.utf8 es_ES@euro es_ES.iso88591 es_ES.iso885915@euro es_ES.utf8 \
es_GT.iso88591 es_GT.utf8 es_HN.iso88591 es_HN.utf8 es_MX.iso88591 es_MX.utf8 es_NI.iso88591 es_NI.utf8 \
es_PA.iso88591 es_PA.utf8 es_PE.iso88591 es_PE.utf8 es_PR.iso88591 es_PR.utf8 es_PY.iso88591 es_PY.utf8 \
es_SV.iso88591 es_SV.utf8 es_US.iso88591 es_US.utf8 es_UY.iso88591 es_UY.utf8 es_VE.iso88591 es_VE.utf8)"
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
SETLANGUAGE_2="0"
exit
fi
SETLANGUAGE=$SETLANGUAGE_2
elif [[ "$SETLANGUAGE" == "2" ]];then
SETLANGUAGE_2="$(zenity --width=400 --height=380 --list --column "" --title="Establecer Idioma - Inglés - English" \
en_AG.utf8 en_AU.iso88591 en_AU.utf8 en_BW.iso88591 en_BW.utf8 en_CA.iso88591 en_CA.utf8 \
en_DK.iso88591 en_DK.utf8 en_GB.iso88591 en_GB.utf8 en_HK.iso88591 en_HK.utf8 en_IE@euro en_IE.iso88591 en_IE.iso885915@euro en_IE.utf8 \
en_IN.utf8 en_NG.utf8 en_NZ.iso88591 en_NZ.utf8 en_PH.iso88591 en_PH.utf8 \
en_SG.iso88591 en_SG.utf8 en_US.iso88591 en_US.utf8 en_ZA.iso88591 en_ZA.utf8 en_ZW.iso88591 en_ZW.utf8)"
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
SETLANGUAGE_2="0"
exit
fi
SETLANGUAGE=$SETLANGUAGE_2
elif [[ "$SETLANGUAGE" == "3" ]];then
SETLANGUAGE_2="$(zenity --width=400 --height=380 --list --column "" --title="Establecer Idioma - Portugués - Português" \
pt_BR.iso88591 pt_BR.utf8 pt_PT@euro pt_PT.iso88591 pt_PT.iso885915@euro pt_PT.utf8)"
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
SETLANGUAGE_2="0"
exit
fi
SETLANGUAGE=$SETLANGUAGE_2
elif [[ "$SETLANGUAGE" == "4" ]];then
SETLANGUAGE_2="$(zenity --width=400 --height=380 --list --column "" --title="Establecer Idioma - Ruso - Русский язык" \
ru_RU.iso88595 ru_RU.koi8r ru_RU.utf8 ru_UA.koi8u ru_UA.utf8)"
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
SETLANGUAGE_2="0"
exit
fi
SETLANGUAGE=$SETLANGUAGE_2
else
echo ""
fi
}

function set_language_xkb(){
SETXKEYBOARD="$(zenity --width=400 --height=380 --list --column "Lang." --column "Desc." --title="Establecer Idioma del teclado" \
es "(Castellano - Spanish)" \
latam "(Latino Americano)" \
pt "(Portugués - Português)" \
ru "(Ruso - Русский язык)" \
us "(Inglés - English)")"
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
SETXKEYBOARD="0"
exit
fi
}

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
help
exit 0
elif [[ "$1" = "-e" ]]; then
set_language
echo "El idioma elegido es: $SETLANGUAGE"
cat << EOT > /etc/profile.d/05-i18n.sh
# Begin /etc/profile.d/05-i18n.sh
export LANG=$SETLANGUAGE
export LANGUAGE=$SETLANGUAGE
export LC_MESSAGES=$SETLANGUAGE
# End /etc/profile.d/05-i18n.sh
EOT
exit 0
elif [[ "$1" = "-b" ]]; then
if [[ ${2} = "" ]];then
echo "No ha introducido ningún idioma"
else
cat << EOT > /etc/profile.d/05-i18n.sh
# Begin /etc/profile.d/05-i18n.sh
export LANG=${2}
export LANGUAGE=${2}
export LC_MESSAGES=${2}
# End /etc/profile.d/05-i18n.sh
EOT
echo "El idioma elegido es: ${2}"
exit 0
fi
elif [[ "$1" = "-k" ]]; then
set_language_xkb
echo "El teclado elegido es: $SETXKEYBOARD"
cat << EOT > /etc/profile.d/06-xkeyboard.sh
# Begin /etc/profile.d/06-xkeyboard.sh
if [[ x\$DISPLAY != x ]];then
setxkbmap $SETXKEYBOARD
else
echo ""
fi
# End /etc/profile.d/06-xkeyboard.sh
EOT
elif [[ "$1" = "-n" ]]; then
if [[ ${2} = "" ]];then
echo "No ha introducido ningún teclado"
else
cat << EOT > /etc/profile.d/06-xkeyboard.sh
# Begin /etc/profile.d/06-xkeyboard.sh
if [[ x\$DISPLAY != x ]];then
setxkbmap ${2}
else
echo ""
fi
# End /etc/profile.d/06-xkeyboard.sh
EOT
echo "El teclado elegido es: ${2}"
exit 0
fi
fi
echo ""
echo "Use \"--help\" para más detalles."
#===============Fin de Programa=================#

