#! /bin/sh
#=========================================================#
# /usr/bin/tzconfig
# Libreria para Vegnux NeonatoX OS
# Proyecto Venezolano VegnuX <http://www.vegnux.org.ve>
# Por:
# Carlos Sánchez <mkl.vegnux@gmail.com>
# Nehemias Velasquez <nehe009@gmail.com>
# 2007 - 2013
# GPLv3
# This program comes with ABSOLUTELY NO WARRANTY.
#=========================================================#
#===============Inicio de Programa=================#
#Check if running as root.
if [[ "${UID}" != "0" ]]; then
	echo "No eres usuario Root" 
	exit 1
fi

function help(){
    echo "tzconfig - Proyecto VegnuX 2007-2013 (GPLv3)"
	echo ""
	echo "Uso: tzconfig [OPTION] [ZONA_HORARIA]"
	echo ""
	echo "-h, --help: Muestra esta información."
	echo "-e Asistente basico para establecer la Zona Horaria."
	echo "-b Edita informacion sin asistente."
}

function set_time_zone(){
# menu principal
TZCONFIG="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria" \
"Africa" \
"America" \
"Asia" \
"Australia" \
"Europe")"
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG="0"
exit
fi
# zona horaria Africa
if [[ "$TZCONFIG" == "Africa" ]];then
TZCONFIG_2="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - Africa" \
Abidjan Accra Addis_Ababa Algiers Asmara Asmera Bamako Bangui Banjul Bissau Blantyre Brazzaville \
Bujumbura Cairo Casablanca Ceuta Conakry Dakar Dar_es_Salaam Djibouti Douala El_Aaiun Freetown Gaborone Harare \
Johannesburg Kampala Khartoum Kigali Kinshasa Lagos Libreville Lome Luanda Lubumbashi Lusaka Malabo \
Maputo Maseru Mbabane Mogadishu Monrovia Nairobi Ndjamena Niamey Nouakchott Ouagadougou Porto-Novo Sao_Tome \
Timbuktu Tripoli Tunis Windhoek)"
TZCONFIG=$TZCONFIG/$TZCONFIG_2
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_2="0"
exit
fi
# zona horaria America
elif [[ "$TZCONFIG" == "America" ]];then
TZCONFIG_2="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - America" \
Argentina Indiana Kentucky North_Dakota Adak Anchorage Anguilla Antigua Araguaina Aruba Asuncion Atikokan \
Atka Bahia Barbados Belem Belize Blanc-Sablon Boa_Vista Bogota Boise Buenos_Aires Cambridge_Bay Campo_Grande \
Cancun Caracas Catamarca Cayenne Cayman Chicago Chihuahua Coral_Harbour Cordoba Costa_Rica Cuiaba Curacao \
Danmarkshavn Dawson Dawson_Creek Denver Detroit Dominica Edmonton Eirunepe El_Salvador Ensenada Fort_Wayne Fortaleza \
Glace_Bay Godthab Goose_Bay Grand_Turk Grenada Guadeloupe Guatemala Guayaquil Guyana Halifax Havana Hermosillo \
Indianapolis Inuvik Iqaluit Jamaica Jujuy Juneau Knox_IN La_Paz Lima Los_Angeles Louisville Maceio \
Managua Manaus Marigot Martinique Mazatlan Mendoza Menominee Merida Mexico_City Miquelon Moncton Monterrey \
Montevideo Montreal Montserrat Nassau New_York Nipigon Nome Noronha Panama Pangnirtung Paramaribo Phoenix \
Port-au-Prince Port_of_Spain Porto_Acre Porto_Velho Puerto_Rico Rainy_River Rankin_Inlet Recife Regina Resolute Rio_Branco Rosario \
Santarem Santiago Santo_Domingo Sao_Paulo Scoresbysund Shiprock St_Barthelemy St_Johns St_Kitts St_Lucia St_Thomas St_Vincent \
Swift_Current Tegucigalpa Thule Thunder_Bay Tijuana Toronto Tortola Vancouver Virgin Whitehorse Winnipeg Yakutat \
Yellowknife)"
TZCONFIG=$TZCONFIG/$TZCONFIG_2
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_2="0"
exit
fi
# zona horaria America/Argentina
if [[ "$TZCONFIG_2" == Argentina ]];then
TZCONFIG_3="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - America/Argentina" \
Buenos_Aires Catamarca ComodRivadavia Cordoba Jujuy La_Rioja Mendoza Rio_Gallegos Salta San_Juan San_Luis Tucuman Ushuaia)"
TZCONFIG=$TZCONFIG/$TZCONFIG_3
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_3="0"
exit
fi
# zona horaria America/Indiana
elif [[ "$TZCONFIG_2" == "Indiana" ]];then
TZCONFIG_3="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - America/Indiana" \
Indianapolis Knox Marengo Petersburg Tell_City Vevay Vincennes Winamac)"
TZCONFIG=$TZCONFIG/$TZCONFIG_3
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_3="0"
exit
fi
# zona horaria America/Kentucky
elif [[ "$TZCONFIG_2" == "Kentucky" ]];then
TZCONFIG_3="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - America/Kentucky" \
Louisville Monticello)"
TZCONFIG=$TZCONFIG/$TZCONFIG_3
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_3="0"
exit
fi
# zona horaria America/North_Dakota
elif [[ "$TZCONFIG_2" == "North_Dakota" ]];then
TZCONFIG_3="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - America/North_Dakota" \
Center New_Salem)"
TZCONFIG=$TZCONFIG/$TZCONFIG_3
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_3="0"
exit
fi
else
echo ""
fi
# zona horaria Asia
elif [[ "$TZCONFIG" == "Asia" ]];then
TZCONFIG_2="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - Asia" \
Aden Almaty Amman Anadyr Aqtau Aqtobe Ashgabat Ashkhabad Baghdad Bahrain Baku Bangkok \
Beirut Bishkek Brunei Calcutta Choibalsan Chongqing Chungking Colombo Dacca Damascus Dhaka Dili \
Dubai Dushanbe Gaza Harbin Ho_Chi_Minh Hong_Kong Hovd Irkutsk Istanbul Jakarta Jayapura Jerusalem \
Kabul Kamchatka Karachi Kashgar Kathmandu Katmandu Kolkata Krasnoyarsk Kuala_Lumpur Kuching Kuwait Macao \
Macau Magadan Makassar Manila Muscat Nicosia Novosibirsk Omsk Oral Phnom_Penh Pontianak Pyongyang \
Qatar Qyzylorda Rangoon Riyadh Riyadh87 Riyadh88 Riyadh89 Saigon Sakhalin Samarkand Seoul Shanghai \
Singapore Taipei Tashkent Tbilisi Tehran Tel_Aviv Thimbu Thimphu Tokyo Ujung_Pandang Ulaanbaatar Ulan_Bator Urumqi \
Vientiane Vladivostok Yakutsk Yekaterinburg Yerevan)"
TZCONFIG=$TZCONFIG/$TZCONFIG_2
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_2="0"
exit
fi
# zona horaria Australia
elif [[ "$TZCONFIG" == "Australia" ]];then
TZCONFIG_2="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - Australia" \
ACT Adelaide Brisbane Broken_Hill Canberra Currie Darwin Eucla Hobart LHI Lindeman Lord_Howe \
Melbourne North NSW Perth Queensland South Sydney Tasmania Victoria West Yancowinna)"
TZCONFIG=$TZCONFIG/$TZCONFIG_2
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_2="0"
exit
fi
# zona horaria Europa
elif [[ "$TZCONFIG" == "Europe" ]];then
TZCONFIG_2="$(zenity --width=320 --height=380 --list --column "" --title="Zona Horaria - Europe" \
Amsterdam Andorra Athens Belfast Belgrade Berlin Bratislava Brussels Bucharest Budapest Chisinau Copenhagen \
Dublin Gibraltar Guernsey Helsinki Isle_of_Man Istanbul Jersey Kaliningrad Kiev Lisbon Ljubljana London Luxembourg Madrid \
Malta Mariehamn Minsk Monaco Moscow Nicosia Oslo Paris Podgorica Prague Riga Rome \
Samara San_Marino Sarajevo Simferopol Skopje Sofia Stockholm Tallinn Tirane Tiraspol Uzhgorod Vaduz \
Vatican Vienna Vilnius Volgograd Warsaw Zagreb Zaporozhye Zurich)"
TZCONFIG=$TZCONFIG/$TZCONFIG_2
if [ "$?" = "1" ]; then #chequea si aprete cerrar o cancelar o ESC
TZCONFIG_2="0"
exit
fi
else
echo ""
fi
}

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
help
exit 0
elif [[ "$1" = "-e" ]]; then
set_time_zone
echo "La zona horaria elegida es: ${TZCONFIG}"
cp --remove-destination /usr/share/zoneinfo/${TZCONFIG} /etc/localtime
exit 0
elif [[ "$1" = "-b" ]]; then
if [[ ${2} = "" ]];then
echo "No ha introducido ninguna zona horaria"
else
cp --remove-destination /usr/share/zoneinfo/"${2}" /etc/localtime
echo "La zona horaria elegida es: ${2}"
exit 0
fi
fi
echo ""
echo "Use \"--help\" para más detalles."
#===============Fin de Programa=================#
